// Auto-generated by deployment scripts on 2025-09-08
// Do not edit manually

export interface ContractAddresses {
  FeeConfig: `0x${string}`;
  EventFactory: `0x${string}`;
  ResolutionManager: `0x${string}`;
  USDCToken: `0x${string}`;
  TreasuryAddress: `0x${string}`;
  ArbiterAddress: `0x${string}`;
}

export const SONIC_MAINNET_ADDRESSES: ContractAddresses = {
  FeeConfig: '0x477043dcCeBAeB52F609Fe996BE1502Ed6A3421B',
  EventFactory: '0x40020fefDA001949e9Ea5B900453802F1e7Cb0a1',
  ResolutionManager: '0xe241bEE5b8228Ca03ED6846fe34ce8e743eC0b57',
  USDCToken: '0xD04431DcFe94E99e7399668B60BBe0a350D475E4',
  TreasuryAddress: '0xfeE3Bb04a2c41591789dDeE2E5a104666062aB78',
  ArbiterAddress: '0xfeE3Bb04a2c41591789dDeE2E5a104666062aB78',
} as const;

export const addresses: Record<number, ContractAddresses> = {
  146: SONIC_MAINNET_ADDRESSES, // Sonic Mainnet
};

export const CHAIN_ID = 146;
export const RPC_URL = 'https://rpc.soniclabs.com';